# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: stalin 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "stalin"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tony Spataro"]
  s.date = "2015-02-10"
  s.description = "Kill Web application workers based on arbitrary conditions."
  s.email = "xeger@xeger.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/stalin.rb",
    "lib/stalin/adapter.rb",
    "lib/stalin/adapter/rack.rb",
    "lib/stalin/killer.rb",
    "lib/stalin/watcher.rb",
    "lib/stalin/watcher/linux_proc_statm.rb",
    "lib/stalin/watcher/unix_ps.rb",
    "stalin.gemspec"
  ]
  s.homepage = "https://github.com/xeger/stalin"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Kill rack"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<sinatra>, ["~> 1.4"])
      s.add_development_dependency(%q<unicorn>, ["~> 4.8"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<sinatra>, ["~> 1.4"])
      s.add_dependency(%q<unicorn>, ["~> 4.8"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<sinatra>, ["~> 1.4"])
    s.add_dependency(%q<unicorn>, ["~> 4.8"])
  end
end

